（再度実施）

In [1]:
import pandas as pd
df = pd.read_csv("..\サンプルデータ\sukkiri-ml-codes\datafiles\Bank.csv")
df.head()

<>:2: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
C:\Users\masao\AppData\Local\Temp\ipykernel_16460\411556213.py:2: SyntaxWarning: invalid escape sequence '\s'
  df = pd.read_csv("..\サンプルデータ\sukkiri-ml-codes\datafiles\Bank.csv")
C:\Users\masao\AppData\Local\Temp\ipykernel_16460\411556213.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

,id,age,job,marital,education,default,amount,housing,loan,contact,day,month,duration,campaign,previous,y
0,1,39,blue-collar,married,secondary,no,1756.0,yes,no,cellular,3,apr,370.055237,1,0,1
1,2,51,entrepreneur,married,primary,no,1443.0,no,no,cellular,18,feb,233.998933,10,0,1
2,3,36,management,single,tertiary,no,436.0,no,no,cellular,13,apr,NaN,1,2,0
3,4,63,retired,married,secondary,no,474.0,no,no,cellular,25,jan,252.525808,1,0,0
4,5,31,management,single,tertiary,no,354.0,no,no,cellular,30,apr,NaN,1,2,0

In [2]:
%matplotlib
from sklearn.model_selection import train_test_split

Using matplotlib backend: <object object at 0x000001351689C7A0>

In [4]:
# 文字列データを一気にダミー化
str_col = ["job", "marital", "education", "default", "housing", "loan", "contact", "month"]
str_col_df = pd.get_dummies(df[str_col], drop_first=True, dtype=int)
df2 = pd.concat([df, str_col_df], axis=1)
df2.head()

,id,age,job,marital,education,default,amount,housing,loan,contact,...,month_dec,month_feb,month_jan,month_jul,month_jun,month_mar,month_may,month_nov,month_oct,month_sep
0,1,39,blue-collar,married,secondary,no,1756.0,yes,no,cellular,...,0,0,0,0,0,0,0,0,0,0
1,2,51,entrepreneur,married,primary,no,1443.0,no,no,cellular,...,0,1,0,0,0,0,0,0,0,0
2,3,36,management,single,tertiary,no,436.0,no,no,cellular,...,0,0,0,0,0,0,0,0,0,0
3,4,63,retired,married,secondary,no,474.0,no,no,cellular,...,0,0,1,0,0,0,0,0,0,0
4,5,31,management,single,tertiary,no,354.0,no,no,cellular,...,0,0,0,0,0,0,0,0,0,0

In [5]:
df2.columns

Index(['id', 'age', 'job', 'marital', 'education', 'default', 'amount',
       'housing', 'loan', 'contact', 'day', 'month', 'duration', 'campaign',
       'previous', 'y', 'job_blue-collar', 'job_entrepreneur', 'job_housemaid',
       'job_management', 'job_retired', 'job_self-employed', 'job_services',
       'job_student', 'job_technician', 'job_unemployed', 'job_unknown',
       'marital_married', 'marital_single', 'education_secondary',
       'education_tertiary', 'education_unknown', 'default_yes', 'housing_yes',
       'loan_yes', 'contact_sending _document', 'contact_telephone',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep'],
      dtype='object')

In [6]:
#訓練&検証データとテストデータに分割
train_val,test = train_test_split(df2,test_size=0.2,random_state=0)
train_val.head()

,id,age,job,marital,education,default,amount,housing,loan,contact,...,month_dec,month_feb,month_jan,month_jul,month_jun,month_mar,month_may,month_nov,month_oct,month_sep
8940,8941,35,blue-collar,single,secondary,no,-295.0,yes,yes,cellular,...,0,0,0,0,0,0,1,0,0,0
12626,12627,24,blue-collar,single,secondary,no,383.0,no,no,cellular,...,0,0,0,0,0,0,1,0,0,0
23448,23449,39,self-employed,divorced,tertiary,no,1415.0,no,no,sending _document,...,0,0,0,0,1,0,0,0,0,0
24317,24318,50,entrepreneur,married,secondary,no,665.0,no,no,telephone,...,0,0,0,0,0,0,0,1,0,0
15824,15825,46,management,single,tertiary,no,2044.0,no,no,telephone,...,0,1,0,0,0,0,0,0,0,0

In [7]:
# durationの欠損値を平均で補完
duration_mean = train_val["duration"].mean()
train_val2 = train_val.fillna(duration_mean)
train_val2.isnull().sum()

id                           0
age                          0
job                          0
marital                      0
education                    0
default                      0
amount                       0
housing                      0
loan                         0
contact                      0
day                          0
month                        0
duration                     0
campaign                     0
previous                     0
y                            0
job_blue-collar              0
job_entrepreneur             0
job_housemaid                0
job_management               0
job_retired                  0
job_self-employed            0
job_services                 0
job_student                  0
job_technician               0
job_unemployed               0
job_unknown                  0
marital_married              0
marital_single               0
education_secondary          0
education_tertiary           0
education_unknown            0
default_yes                  0
housing_yes                  0
loan_yes                     0
contact_sending _document    0
contact_telephone            0
month_aug                    0
month_dec                    0
month_feb                    0
month_jan                    0
month_jul                    0
month_jun                    0
month_mar                    0
month_may                    0
month_nov                    0
month_oct                    0
month_sep                    0
dtype: int64

In [8]:
# 文字列データを除外
x = train_val2.drop(str_col, axis=1)
# 特徴量としていらない列も除外
x = x.drop(['id','y','day'],axis=1)
# 目的変数
t = train_val2["y"]

# train_val2を訓練用と検証用に分割
x_train, x_test, y_train, y_test = train_test_split(x, t, test_size=0.2, random_state=0)

In [11]:
# 決定木モデルの作成
from sklearn import tree
model = tree.DecisionTreeClassifier(max_depth=5, random_state=0, class_weight="balanced")
model.fit(x_train, y_train)

DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=0)

In [9]:
# 同じ処理を繰り返すのでlearn関数を定義
def learn(x,t,depth):
    x_train,x_val,y_train,y_val = train_test_split(x,t,test_size=0.2,random_state=13)

    datas=[x_train,x_val,y_train,y_val]

    model = tree.DecisionTreeClassifier(random_state=depth,max_depth=depth,class_weight='balanced')
    model.fit(x_train,y_train)
    train_score=model.score(x_train,y_train)
    
    val_score=model.score(x_val,y_val)
    return train_score,val_score,model,datas

In [12]:
# 深さを変えてモデル作成
for i in range(1,20):
    s1,s2,model,datas = learn(x,t,i)
    print(i,s1,s2)

# サンプルと同じ結果を得られる

1 0.7163757848050227 0.7138908085694541
2 0.6624042393871321 0.6632112416493895
3 0.6624042393871321 0.6632112416493895
4 0.7275502563216405 0.728864316977655
5 0.7603824664477853 0.7615756738078784
6 0.8037555440354818 0.8051140290255702
7 0.8116467945394851 0.8113337940566689
8 0.8464950175681124 0.8228518774475927
9 0.8678071539657853 0.8332181524994241
10 0.8862968722999828 0.8352914075097904
11 0.8986233511894476 0.8286109191430546
12 0.9162490639940095 0.8269983874683253
13 0.9324347675825125 0.8223911541119557
14 0.9457980531075398 0.824925132457959
15 0.9583549334715742 0.8173231974199493
16 0.9687229998271989 0.8170928357521309
17 0.9787454639709694 0.8173231974199493
18 0.9848511030470595 0.8150195807417646
19 0.9895167329070906 0.8122552407279429

In [13]:
# 深さ10が最大性能だった

#特徴量重要度の確認
pd.Series(model.feature_importances_,index=x.columns).sort_values(ascending=False)

# やはりdurationが強いことがわかる

duration                     0.455823
age                          0.110480
amount                       0.095696
campaign                     0.091105
housing_yes                  0.057687
loan_yes                     0.030799
previous                     0.018907
contact_sending _document    0.018649
job_blue-collar              0.009632
education_secondary          0.008948
marital_single               0.007972
marital_married              0.007658
job_technician               0.007154
job_services                 0.006878
job_management               0.006178
month_jun                    0.005819
month_jul                    0.005668
month_aug                    0.005315
month_may                    0.004786
job_retired                  0.004706
education_tertiary           0.004246
contact_telephone            0.003933
month_feb                    0.003789
month_nov                    0.003654
job_housemaid                0.003163
education_unknown            0.002902
job_unemployed               0.002834
job_self-employed            0.002809
job_entrepreneur             0.002601
month_oct                    0.002145
month_jan                    0.001994
month_mar                    0.001798
job_student                  0.001441
default_yes                  0.001149
month_dec                    0.000745
month_sep                    0.000678
job_unknown                  0.000262
dtype: float64

モデルの改善

In [14]:
# さっきはdurationを平均で穴埋めしたが、クロス集計で穴埋めする値を最適化していきたい

# 文字列データから集計するdurationの平均を決める
str_col

['job',
 'marital',
 'education',
 'default',
 'housing',
 'loan',
 'contact',
 'month']

In [15]:
# そこで、どの変数においてy=1になる割合が多いか確認する
for name in str_col:
    print(train_val.groupby(name)['y'].mean())
    print("next=========")

# contact, loan, housingが0.4になっており、y=1になる割合が高い

job
admin.           0.311699
blue-collar      0.354396
entrepreneur     0.382749
housemaid        0.282430
management       0.308227
retired          0.368468
self-employed    0.292047
services         0.328203
student          0.153846
technician       0.305648
unemployed       0.238019
unknown          0.308725
Name: y, dtype: float64
next=========
marital
divorced    0.331283
married     0.340136
single      0.269984
Name: y, dtype: float64
next=========
education
primary      0.350904
secondary    0.319463
tertiary     0.299780
unknown      0.339188
Name: y, dtype: float64
next=========
default
no     0.320747
yes    0.240209
Name: y, dtype: float64
next=========
housing
no     0.215788
yes    0.401488
Name: y, dtype: float64
next=========
loan
no     0.299588
yes    0.422426
Name: y, dtype: float64
next=========
contact
cellular             0.276659
sending _document    0.415632
telephone            0.315481
Name: y, dtype: float64
next=========
month
apr    0.316501
aug    0.247312
dec    0.346939
feb    0.256800
jan    0.212030
jul    0.310688
jun    0.357845
mar    0.346320
may    0.387578
nov    0.234857
oct    0.301136
sep    0.311419
Name: y, dtype: float64
next=========

In [16]:
# loan * housing でdurationの平均を集計
pd.pivot_table(train_val,index="housing",columns="loan",values="duration")

loan             no         yes
housing
no       237.824421  299.867693
yes      332.885094  439.809380

In [18]:
# 穴埋め処理を関数として定義
def nan_fill(train_val):
    isnull = train_val['duration'].isnull()

    train_val2 = train_val.copy()
    #housing=yesの処理
    train_val2.loc[(isnull) & (train_val2['housing']=='yes') 
                  &(train_val2['loan']=='yes'),'duration' ]=439
    train_val2.loc[(isnull) & (train_val2['housing']=='yes') 
                  &(train_val2['loan']=='no'),'duration' ]=332

    #housing=noの処理
    train_val2.loc[(isnull) & (train_val2['housing']=='no') 
                  &(train_val2['loan']=='yes'),'duration' ]=301
    train_val2.loc[(isnull) & (train_val2['housing']=='no') 
                  &(train_val2['loan']=='no'),'duration' ]=237
    
    return train_val2

In [19]:
# train_val2を変更
train_val2=nan_fill(train_val)

In [20]:
train_val2.isnull().sum()

id                           0
age                          0
job                          0
marital                      0
education                    0
default                      0
amount                       0
housing                      0
loan                         0
contact                      0
day                          0
month                        0
duration                     0
campaign                     0
previous                     0
y                            0
job_blue-collar              0
job_entrepreneur             0
job_housemaid                0
job_management               0
job_retired                  0
job_self-employed            0
job_services                 0
job_student                  0
job_technician               0
job_unemployed               0
job_unknown                  0
marital_married              0
marital_single               0
education_secondary          0
education_tertiary           0
education_unknown            0
default_yes                  0
housing_yes                  0
loan_yes                     0
contact_sending _document    0
contact_telephone            0
month_aug                    0
month_dec                    0
month_feb                    0
month_jan                    0
month_jul                    0
month_jun                    0
month_mar                    0
month_may                    0
month_nov                    0
month_oct                    0
month_sep                    0
dtype: int64

In [21]:
t =train_val2['y']
x = train_val2.drop(str_col,axis=1)
x =x.drop(['id','y','day'],axis=1)

for i in range(1,20):
    s1,s2,model,datas = learn(x,t,i)
    print(i,s1,s2)

1 0.7497839986175912 0.751209398756047
2 0.7497839986175912 0.751209398756047
3 0.7548528310581187 0.7551255471089611
4 0.7507056045158689 0.7542041004376872
5 0.7804849951039686 0.7820778622437227
6 0.7835954150106561 0.7795438838977194
7 0.8081331720523012 0.8002764340013822
8 0.8490870341570186 0.8375950241879752
9 0.8660791429065146 0.8364432158488827
10 0.8834168538678647 0.8316056208246948
11 0.8936121191175623 0.8228518774475927
12 0.9155578595703012 0.8302234508177839
13 0.9262715281377801 0.81571066574522
14 0.9411900236161511 0.8113337940566689
15 0.954150106560682 0.8131766873992168
16 0.9676285928229941 0.8166321124164939
17 0.9747710385346466 0.8115641557244875
18 0.9814526812971603 0.815249942409583
19 0.9871551177927539 0.8129463257313982

In [22]:
# テストデータでスコア確認
model_tree=tree.DecisionTreeClassifier(max_depth=10,random_state=10,class_weight="balanced")
model_tree.fit(x,t)

test2=nan_fill(test)
t =test2['y']
x = test2.drop(str_col,axis=1)
x =x.drop(['id','y','day'],axis=1)
model_tree.score(x,t)

0.8145963877626244